### PR TITLE
Update office-365-developer-program-faq.md

### PR DESCRIPTION
**Pull request by imba-tjd**

### CODE REVIEW

**Comment by imba-tjd** [comment]
@CeciAc @nokura @JasonCard Hi. It seems that the localization team doesn't review any of the PRs under this organization.

**Comment by JasonCard** [comment]
Hi @TinaMcN, 
Do you own this repo? If so, can you please help to follow up on this PR?

cc @SonjaSaltzman @nokura @CeciAc

**Comment by TinaMcN** [comment]
@JasonCard yes I own this repo.  @OfficeGlobal please implement the changes as suggested (there are 4 broken/exposed links in the "Office 365 开发人员订阅中包含什么内容"  (What's included in the Office 365 developer subscription?) section.  Note this is a human translated topic.  
@imba-tjd thank you for reporting this issue!   If you find any other translation issues in this repo please assign to or mention @OfficeGlobal

**Comment by OfficeGlobal** [comment]
@imba-tjd , @TinaMcN , @JasonCard  the article has been updated and published live (https://docs.microsoft.com/zh-cn/office/developer-program/office-365-developer-program-faq)

**Comment by imba-tjd** [comment]
It's OK for me to just close my PR, but I suggest you following a normal open source workflow...

**Pull request closed without merging**
